### ISSUE TITLE
建议使用 github + 加速源 来分发下载资源包

### ISSUE THREAD

**Issue by zkitefly** [LocalizedMC/I18nUpdataMod-NLTS-LegacyFabric#1]
https://github.com/TexTrueStudio/I18nUpdateMod-NLTS/issues/8

因为服务器压力过大，我的建议是使用 github + 加速源 来分发下载资源包

我这边已经准备好了 https://github.com/zkitefly/I18nUpdateMod-resources#readme

将所有链接的 http://downloader1.meitangdehulu.com:22943/ 替换成 https://cdn.staticaly.com/gh/zkitefly/I18nUpdateMod-resources/main/files/

不知可否？

**Comment by TexBlock** [comment]
通用issue请在 https://github.com/TexTrueStudio/I18nUpdateMod-NLTS/issues 反馈
